import {spawn} from 'node:child_process';
import {chromium} from 'playwright';
import {temporaryData,browserOptions} from './tests/helpers.mjs';
import assert from 'node:assert/strict';
import {titleFor,roles} from './public/story.js';
for(let i=0;i<5;i++)assert.equal(titleFor([i,i,i]),roles[i]);
assert.equal(titleFor([0,1,2]),'Vigilante Hacker');assert.equal(titleFor([4,3,4]),'Conscientious Hacker');assert.equal(titleFor([]),'Operative');

const child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'4175',DATA_DIR:temporaryData(),NODE_ENV:'development',REQUIRE_INVITES:'false'},stdio:['ignore','pipe','pipe']});let browser;
try{
 const adminUrl=await new Promise((resolve,reject)=>{let output='';child.stdout.on('data',d=>{output+=d;const m=output.match(/Admin: (http[^\r\n]+)/);if(m)resolve(m[1]);});child.on('error',reject);});
 browser=await chromium.launch(browserOptions);const preview=await browser.newPage(),errors=[];preview.on('pageerror',e=>errors.push(e.message));
 await preview.goto('http://localhost:4175/intro');await preview.locator('#codename').fill('Ahmed');await preview.locator('#vn-enrol button').click();await preview.locator('[data-story="next"]').click();assert.equal(await preview.locator('[data-choice]').count(),5);assert(await preview.locator('[data-story="next"]').isDisabled());
 for(const width of [1280,736,360,320]){await preview.setViewportSize({width,height:1000});assert(await preview.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow at ${width}`);const buttons=await preview.locator('[data-choice]').all();for(const b of buttons){const box=await b.boundingBox();assert(box.height>=35);}}
 for(let i=0;i<3;i++){await preview.locator('[data-choice="4"]').click();await preview.locator('[data-story="next"]').click();}await preview.waitForFunction(()=>document.querySelector('.vn-title strong')?.textContent==='Conscientious Hacker Ahmed');
 assert(await preview.locator('[data-story="back"]').isDisabled());await preview.reload();await preview.locator('#my-name').filter({hasText:'Conscientious Hacker Ahmed'}).waitFor();assert.equal(await preview.locator('#leave').count(),0);
 for(const id of ['speed-control','rate-feedback','mobile-suspicion','mobile-extract','map']){await preview.locator('.tour-box').waitFor();assert(await preview.locator('#'+id).evaluate(e=>e.classList.contains('tour-highlight')));const b=await preview.locator('.tour-box').boundingBox();assert(b.x>=0&&b.x+b.width<=320&&b.y>=0&&b.y+b.height<=1000);await preview.locator('#tour-next').click();}assert.equal(await preview.locator('.tour-box').count(),0);await preview.reload();await preview.locator('#quick-guide').waitFor();assert.equal(await preview.locator('.tour-box').count(),0);await preview.locator('#quick-guide').click();await preview.locator('#tour-skip').click();assert.equal(await preview.locator('.tour-highlight').count(),0);
 const host=await browser.newPage();await host.goto(adminUrl);const player=await browser.newPage();player.on('pageerror',e=>errors.push(e.message));await player.goto('http://localhost:4175/player');await player.locator('#nickname').fill('Sara');await player.locator('button[type="submit"]').click();await player.locator('#my-name').waitFor();await host.locator('#play-intro').click();await player.locator('#story-stage').waitFor({state:'visible'});assert.equal(await player.locator('[data-story]').count(),0);
 const before=await (await fetch('http://localhost:4175/api/state')).json();
 for(let i=0;i<3;i++){await host.locator('[data-story="next"]').click();await player.waitForFunction(n=>document.querySelector('.story-stage').dataset.scene===String(n),i+1);await player.locator('[data-choice="1"]').click();await player.locator('[data-choice="1"][aria-pressed="true"]').waitFor();}
 await host.locator('[data-story="next"]').click();await player.waitForFunction(()=>document.querySelector('.vn-title strong').textContent==='Watchkeeper Sara');const after=await (await fetch('http://localhost:4175/api/state')).json();for(const key of ['points','gain','bank','coverage','speed','suspicion','queries'])assert.equal(after.players[1][key],before.players[1][key],`choice changed gameplay ${key}`);
 const denied=await player.evaluate(async()=>{const token=localStorage.getItem('mirror-player-token');return Promise.all([['/api/story-choice',{scene:3,option:3}],['/api/player',{name:'NewName',title:'Mastermind'}]].map(async([path,body])=>(await fetch(path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)})).status));});assert.deepEqual(denied,[403,403]);
 await player.reload();await player.locator('.vn-title').waitFor({state:'visible'});assert.equal(await player.locator('.vn-title strong').innerText(),'Watchkeeper Sara');await host.locator('[data-story="next"]').click();await player.locator('.layout').waitFor({state:'visible'});assert.equal(await player.locator('#my-name').innerText(),'Watchkeeper Sara');assert.deepEqual(errors,[]);console.log('PASS: all five titles, majority/ties, anime VN choices, mobile layout, independent player title, reload persistence, no gameplay effects, host-only progression.');
}finally{await browser?.close();child.kill();}
