import assert from 'node:assert/strict';
import {startServer,sleep} from './helpers.mjs';
let s=await startServer({port:4180,env:{REQUIRE_INVITES:'true',ALLOW_DEMO_BOTS:'false'}});
try{
 const root=await fetch(s.url);assert.match(root.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(root.headers.get('referrer-policy'),'no-referrer');assert.equal((await fetch(s.url+'/.env')).status,404);assert.equal((await fetch(s.url+'/data/game.sqlite')).status,404);
 assert.equal((await s.post('/api/admin',{action:'invites'},'bad')).status,401);assert.equal((await s.post('/api/join',{name:'Ahmed',room:'MIRROR'})).status,403);
 const codes=(await s.post('/api/admin',{action:'invites',count:3},s.key)).body.codes;assert.equal(codes.length,3);const raw=JSON.stringify(await s.get());for(const code of codes)assert(!raw.includes(code),'invitation leaked');assert(!raw.includes(s.key));
 const joined=await s.post('/api/join',{name:'Ahmed',room:'MIRROR',invite:codes[0],origin:true});assert.equal(joined.status,200);const token=joined.body.token,cookie=joined.headers.get('set-cookie').split(';')[0];assert.match(joined.headers.get('set-cookie'),/HttpOnly/);
 assert.equal((await s.post('/api/join',{name:'Clone',room:'MIRROR',invite:codes[0]})).status,403);const reused=await s.post('/api/join',{name:'Changed',room:'MIRROR',invite:codes[1]},undefined,{Cookie:cookie});assert.equal(reused.body.id,joined.body.id);assert.equal((await s.get()).players.length,1);
 assert.equal((await s.post('/api/player',{extracting:true},token)).status,409);assert.equal((await s.post('/api/origin-finish',{choices:[4,4,4]},token)).status,200);assert.equal((await s.post('/api/origin-finish',{choices:[0,0,0]},token)).status,409);
 const attacks=[{tuned:[1,2,3]},{confirmTune:'speed'},{points:999},{gain:999},{bank:999},{quality:100},{suspicion:0},{id:'another-player'},{title:'Mastermind'},{name:'Other'},{storyChoices:[0,0,0]},{speed:'100'},{speed:null},{speed:7,extracting:'true'}];
 for(const b of attacks)assert((await s.post('/api/player',b,token)).status>=400,'tampering accepted '+JSON.stringify(b));assert.equal((await s.get()).players[0].points,0);
 assert.equal((await s.post('/api/admin',{action:'next'},token)).status,401);assert.equal((await s.post('/api/player',{variety:100},token)).status,403);assert.equal((await s.post('/api/player',{speed:100000},token)).status,200);assert.equal((await s.get()).players[0].speed,10);
 assert.equal((await s.post('/api/player',{speed:7},token,{Origin:'https://evil.example'})).status,403);assert.equal((await s.post('/api/answer',{level:1,option:1},token)).status,409);
 await s.post('/api/admin',{action:'next'},s.key);assert.equal((await s.post('/api/player',{extracting:true},token)).status,409);await s.post('/api/admin',{action:'move',id:joined.body.id,direction:'forward'},s.key);const pre=(await s.get()).players[0];
 const wrong=await s.post('/api/answer',{level:1,option:0},token);assert.equal(wrong.body.correct,false);assert.equal((await s.get()).players[0].points,-5);assert.equal((await s.post('/api/answer',{level:1,option:1},token)).status,429);await sleep(2100);assert.equal((await s.post('/api/answer',{level:1,option:1},token)).body.correct,true);assert.equal((await s.post('/api/answer',{level:1,option:1},token)).status,409);assert((await s.get()).players[0].quality<pre.quality);
 assert.equal((await s.post('/api/player',{extracting:true},token)).status,409);assert.equal((await s.post('/api/player',{spacing:25,extracting:true,confirmTune:'spacing'},token)).status,409);
 const beforeRestart=await s.get(),dataDir=s.dataDir,key=s.key;await s.stop();s=await startServer({port:4180,dataDir,env:{REQUIRE_INVITES:'true',ALLOW_DEMO_BOTS:'false'}});assert.equal(s.key,key);let recovered=await s.get();assert.equal(recovered.players[0].name,'Ahmed');assert.equal(recovered.players[0].title,'Conscientious Hacker');assert.equal(recovered.players[0].points,5);assert.equal(recovered.players[0].quality,beforeRestart.players[0].quality);assert.equal((await s.post('/api/player',{action:'resume'},token)).status,200);
 assert.equal(recovered.players[0].tuneRequired.field,'spacing');assert.equal((await s.post('/api/player',{extracting:true},token)).status,409);assert.equal((await s.post('/api/player',{confirmTune:'spacing'},token)).status,400);assert.equal((await s.post('/api/player',{spacing:65,confirmTune:'spacing'},token)).status,200);assert.equal((await s.get()).players[0].tuneRequired,null);assert.equal((await s.post('/api/player',{extracting:true},token)).status,200);
 await s.post('/api/admin',{action:'start'},s.key);await s.stop();s=await startServer({port:4180,dataDir,env:{REQUIRE_INVITES:'true'}});recovered=await s.get();assert.equal(recovered.status,'paused');assert.equal(recovered.players[0].extracting,false);assert.equal(recovered.players[0].connected,false);
 assert.equal((await s.post('/api/admin',{action:'bots'},s.key)).status,200);assert.equal((await s.post('/api/admin',{action:'newEvent'},s.key)).status,400);await s.post('/api/admin',{action:'newEvent',confirm:'NEW EVENT'},s.key);assert.equal((await s.post('/api/player',{action:'resume'},token)).status,401);
 // No real secret is included in a public snapshot, even during a populated event.
 assert(!JSON.stringify(await s.get()).includes(token));
 console.log('PASS: invitations, duplicate sessions, immutable identities, score/slider tampering, role permissions, origin checks, answer replay/cooldown, SQLite recovery, safe live restart and new-event invalidation.');
}finally{await s.stop();}
