import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {startServer,browserOptions,sleep} from './helpers.mjs';
const s=await startServer({port:4183});let browser;
try{
 const joined=await s.post('/api/join',{name:'ViewportLongNicknameTest',room:'MIRROR',storyChoices:[4,4,4]});browser=await chromium.launch(browserOptions);const context=await browser.newContext({hasTouch:true}),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(s.url+'/player');await page.evaluate(t=>{localStorage.setItem('mirror-player-token',t);localStorage.setItem('mirror-tour-'+t,'seen');},joined.body.token);await page.reload();await page.locator('#my-name').filter({hasText:'Viewport'}).waitFor();
 const sizes=[[1920,1080],[1366,768],[1280,720],[1024,768],[768,1024],[430,932],[390,844],[360,640],[320,568]];
 async function check(label,selectors){await sleep(150);const overflow=await page.evaluate(()=>({x:document.documentElement.scrollWidth>innerWidth,y:document.documentElement.scrollHeight>innerHeight}));assert(!overflow.x&&!overflow.y,`${label}: document overflow`);for(const selector of selectors){const b=await page.locator(selector).boundingBox();assert(b&&b.x>=-1&&b.y>=-1&&b.x+b.width<=page.viewportSize().width+1&&b.y+b.height<=page.viewportSize().height+1,`${label}: ${selector} outside viewport ${JSON.stringify(b)}`);}}
 for(const [width,height]of sizes){await page.setViewportSize({width,height});if(width<=850)await page.locator('button[data-panel="controls"]').tap();await check(`${width}x${height} open access`,['#speed','#rate-feedback',width<=850?'#mobile-extract':'#extract',width<=850?'#mobile-suspicion':'#suspicion-meter']);}
 for(let level=1;level<=3;level++){await s.post('/api/admin',{action:'next'},s.key);await page.locator('[data-answer]').first().waitFor();for(const [width,height]of sizes){await page.setViewportSize({width,height});if(width<=850)await page.locator('button[data-panel="controls"]').tap();await check(`${width}x${height} quiz ${level}`,['#challenge-panel','[data-answer="2"]',width<=850?'#mobile-extract':'#extract']);}await s.post('/api/answer',{level,option:[null,1,2,0][level]},joined.body.token);await page.locator('#challenge-panel').waitFor({state:'hidden'});const field=[null,'spacing','variety','verification'][level];for(const [width,height]of sizes){await page.setViewportSize({width,height});await check(`${width}x${height} tune guide ${level}`,['#tuning-guide','#confirm-tune','#'+field,width<=850?'#mobile-extract':'#extract']);assert(await page.locator(width<=850?'#mobile-extract':'#extract').isDisabled());}await page.locator('#confirm-tune').click();await page.waitForFunction(()=>!document.getElementById('extract').disabled);}
 for(const [width,height]of sizes){await page.setViewportSize({width,height});if(width<=850)await page.locator('button[data-panel="controls"]').tap();await check(`${width}x${height} four sliders`,['#speed','#spacing','#variety','#verification','#rate-feedback',width<=850?'#mobile-extract':'#extract']);if(width<=850){await page.locator('button[data-panel="race"]').tap();await check(`${width}x${height} race`,['#map','#mobile-suspicion','#mobile-extract']);}}
 await page.emulateMedia({reducedMotion:'reduce'});
 for(const [width,height]of sizes){await page.setViewportSize({width,height});if(width<=850)await page.locator('button[data-panel="race"]').tap();await sleep(150);const stage=await page.locator('#aya-stage').boundingBox();for(const selector of ['.aya-face','.aya-antenna']){const part=await page.locator('#aya-stage '+selector).boundingBox();assert(part&&stage&&part.y>=stage.y&&part.y+part.height<=stage.y+stage.height&&part.x>=stage.x&&part.x+part.width<=stage.x+stage.width,`${width}x${height}: clipped robot ${selector}`);}if(width>850&&height>=820){const size=await page.locator('.controls .label-row').first().evaluate(e=>parseFloat(getComputedStyle(e).fontSize));assert(size>=14,'roomy desktop must use readable control text');}}
 assert.deepEqual(errors,[]);console.log('PASS: normal-zoom viewport, unclipped robot, readable roomy-desktop text, all sliders, all quizzes and phone race controls at '+sizes.map(s=>s.join('x')).join(', '));
}finally{await browser?.close();await s.stop();}
